# Generated by Django 4.1 on 2024-03-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewrating', '0002_apprating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
