# Generated by Django 4.1 on 2024-03-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewrating', '0003_rating_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprating',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
