# Generated by Django 4.1 on 2024-04-01 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewrating', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
