# Generated by Django 4.1 on 2024-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupon_discount_amount_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
