# Generated by Django 4.1 on 2024-03-25 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_alter_order_order_status_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.PositiveIntegerField()),
                ('payment_mode', models.CharField(choices=[('khalti', 'Khalti'), ('esewa', 'Esewa'), ('cod', 'Cash On Ddelivery')], max_length=100)),
                ('refrence_id', models.CharField(default='cod', max_length=4000)),
                ('remarks', models.CharField(max_length=3000)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Paid'), ('half', 'Half Payment'), ('cod', 'Cash On Delivery'), ('refunded', 'Refunded')], max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='order.order')),
            ],
        ),
    ]
