# Generated by Django 4.1 on 2024-03-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='remarks',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
