# Generated by Django 4.1 on 2024-03-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ammount',
            field=models.FloatField(),
        ),
    ]
