# Generated by Django 4.1 on 2024-04-04 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_product'),
        ('appointment', '0001_initial'),
        ('payment', '0002_rename_remarks_paymentfail_server_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='order.order'),
        ),
        migrations.AlterField(
            model_name='paymentfail',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_fail', to='order.order'),
        ),
        migrations.AlterField(
            model_name='paymentservice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='appointment.checkoutappointment'),
        ),
    ]
