# Generated by Django 4.1 on 2024-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_order_alter_paymentfail_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfail',
            name='services_product',
            field=models.CharField(default='product', max_length=100),
            preserve_default=False,
        ),
    ]
