# Generated by Django 4.1 on 2024-04-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appointment/services')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('number_of_staffs', models.IntegerField(default=1)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appointment.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_date', models.DateField()),
                ('checkout_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_items', to='appointment.checkoutappointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_items', to='appointment.services')),
                ('slots', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_items', to='appointment.slots')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'unpaid')], max_length=255)),
                ('appointment_status', models.CharField(choices=[('confirmed', 'confirmed'), ('not-attened', 'Not Attened'), ('cancelled', 'cancelled')], max_length=255)),
                ('payment_mode', models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('fonepay', 'FonePay'), ('offline', 'offline')], max_length=255)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('checkout_appointment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_order', to='appointment.checkoutappointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicesitems',
            constraint=models.UniqueConstraint(fields=('checkout_appointment', 'slots'), name='checkout_service_slots_unique'),
        ),
    ]
