# Generated by Django 4.1 on 2024-03-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slots',
            name='number_of_staffs',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='public_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='number_of_staffs',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='BookedAppointment',
        ),
    ]
