# Generated by Django 4.1 on 2024-04-05 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='checkout_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_order', to='appointment.checkoutappointment'),
        ),
        migrations.AlterField(
            model_name='servicesitems',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_items', to='appointment.services'),
        ),
    ]
