# Generated by Django 4.1 on 2024-03-22 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slots',
            name='from_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='slots',
            name='to_time',
            field=models.TimeField(),
        ),
    ]
