# Generated by Django 4.1 on 2024-04-06 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_alter_appointment_checkout_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesitems',
            name='slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_items', to='appointment.slots'),
        ),
    ]
