# Generated by Django 4.1 on 2024-03-26 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_appointment_date_alter_slots_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment', to='appointment.slots'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Appointment', to='appointment.services'),
            preserve_default=False,
        ),
    ]
