# Generated by Django 4.1 on 2024-03-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_remove_slots_number_of_staffs_remove_slots_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='slots',
        ),
        migrations.AddField(
            model_name='services',
            name='from_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='services',
            name='to_time',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
