# Generated by Django 4.1 on 2024-03-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_services_slots_services_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='services',
            name='number_of_staffs',
        ),
        migrations.RemoveField(
            model_name='services',
            name='to_time',
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('number_of_staffs', models.IntegerField(default=1)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='appointment.services')),
            ],
        ),
    ]
