# Generated by Django 4.1 on 2024-03-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_services_from_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slots',
            old_name='time_slot',
            new_name='from_time',
        ),
        migrations.RemoveField(
            model_name='slots',
            name='date',
        ),
        migrations.AddField(
            model_name='slots',
            name='to_time',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
