# Generated by Django 4.1 on 2024-03-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_services_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'unpaid')], default='paid', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('esewa', 'Esewa'), ('khalti', 'Khalti'), ('fonepay', 'FonePay'), ('offline', 'offline')], max_length=255),
        ),
    ]
