# Generated by Django 4.1 on 2024-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointment_number_of_staffs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesitems',
            name='service_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesitems',
            name='service_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
