# Generated by Django 4.1 on 2024-03-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('not-attened', 'unpaid'), ('cancelled', 'cancelled')], default='confirmed', max_length=255),
        ),
    ]
