# Generated by Django 4.1 on 2024-03-27 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointment.slots'),
        ),
    ]
