# Generated by Django 4.1 on 2024-03-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appointment_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('not-attened', 'Not Attened'), ('cancelled', 'cancelled'), ('checkout', 'cancelled')], default='checkout', max_length=255),
        ),
    ]
