# Generated by Django 4.1 on 2024-03-27 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0010_alter_appointment_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slots',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ServicesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_date', models.DateField()),
                ('checkout_appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services_items', to='appointment.checkoutappointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointment.services')),
                ('slots', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointment.slots')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='checkout_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_order', to='appointment.checkoutappointment'),
            preserve_default=False,
        ),
    ]
