# Generated by Django 4.1 on 2024-03-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_checkoutappointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='checkout_appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='appointments_order', to='appointment.checkoutappointment'),
        ),
    ]
