# Generated by Django 4.1 on 2024-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_servicesitems_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('not-attened', 'Not Attened'), ('cancelled', 'cancelled')], max_length=255),
        ),
    ]
