# Generated by Django 4.1 on 2024-04-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(max_length=300),
        ),
    ]
