# Generated by Django 4.1 on 2024-03-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='location',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='provience',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home Address'), ('office', 'Office Address'), ('other', 'other Address')], max_length=255),
        ),
    ]
