# Generated by Django 4.1 on 2024-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_shippingaddress_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='provider',
            field=models.PositiveSmallIntegerField(choices=[(1, 'system'), (2, 'google'), (3, 'facebook'), (4, 'apple')], default=1),
        ),
    ]
