# Generated by Django 4.1 on 2024-08-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default=None, error_messages={'unique': 'Given Mobile Number has already been registered.'}, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
    ]
