# Generated by Django 4.1 on 2024-03-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_shippingaddress_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
