# Generated by Django 4.1 on 2024-03-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_shippingaddress_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
