# Generated by Django 4.1 on 2024-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_shippingaddress_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'SUPER_ADMIN'), (2, 'ADMIN'), (5, 'USER')], default=5, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
