# Generated by Django 4.1 on 2024-03-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compaign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='imge',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='imge',
        ),
    ]
