# Generated by Django 4.1 on 2024-03-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_category_variation_group_category_variations'),
        ('variations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariationGroup',
        ),
    ]
