# Generated by Django 4.1 on 2024-03-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_delete_variationgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
