# Generated by Django 4.1 on 2024-03-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0003_alter_variation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
