# Generated by Django 4.1 on 2024-03-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0004_alter_variation_name_alter_variationoption_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationoption',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='variations.variation'),
        ),
    ]
