# Generated by Django 4.1 on 2024-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('shipped', 'shipped'), ('checkout', 'checkout')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'unpaid'), ('half', 'Half Payment'), ('cod', 'Cash On Delivery'), ('refunded', 'Refunded')], default='cod', max_length=255),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
