# Generated by Django 4.1 on 2024-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price_with_variation',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
