# Generated by Django 4.1 on 2024-03-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_products_order_products_variations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('in-progress', 'In Progress'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('shipped', 'shipped')], max_length=255),
        ),
    ]
