# Generated by Django 4.1 on 2024-03-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_total_discount_orderitem_discount'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user', 'coupons'), name='limit_coupon'),
        ),
    ]
