# Generated by Django 4.1 on 2024-03-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
        ('products', '0001_initial'),
        ('order', '0003_remove_cart_products_cart_product_cart_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='products.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='variations',
            field=models.ManyToManyField(related_name='carts', to='variations.variationoption'),
        ),
    ]
