# Generated by Django 4.1 on 2024-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_coupon_discount_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sub_total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
