# Generated by Django 4.1 on 2024-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
        ('order', '0004_alter_cart_product_alter_cart_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='carts', to='variations.variationoption'),
        ),
    ]
