# Generated by Django 4.1 on 2024-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prirce',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
