# Generated by Django 4.1 on 2024-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0005_alter_variationoption_variation'),
        ('order', '0006_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations',
            field=models.ManyToManyField(related_name='order_items', to='variations.variationoption'),
        ),
    ]
