# Generated by Django 4.1 on 2024-04-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_prirce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prirce',
            new_name='price',
        ),
    ]
