# Generated by Django 4.1 on 2024-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_rename_prirce_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variations_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
