# Generated by Django 4.1 on 2024-03-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
