# Generated by Django 4.1 on 2024-02-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_best_sell',
            field=models.BooleanField(default=False),
        ),
    ]
