# Generated by Django 4.1 on 2024-04-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_name_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_publish',
            field=models.BooleanField(default=True),
        ),
    ]
