# Generated by Django 4.1 on 2024-03-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
