# Generated by Django 4.1 on 2024-02-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_producthaveimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
