# Generated by Django 4.1 on 2024-03-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_delete_variationgroup'),
        ('products', '0006_brand_created_date_brand_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='variations',
        ),
        migrations.AddField(
            model_name='category',
            name='variations',
            field=models.ManyToManyField(related_name='category', to='variations.variationoption'),
        ),
    ]
