# Generated by Django 4.1 on 2024-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailaftervariation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
