# Generated by Django 4.1 on 2024-03-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_category_variations_category_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='descrirption',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
