# Generated by Django 4.1 on 2024-03-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_delete_variationgroup'),
        ('products', '0008_alter_category_descrirption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='variations',
            field=models.ManyToManyField(related_name='category', to='variations.variation'),
        ),
    ]
