# Generated by Django 4.1 on 2024-04-06 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0001_initial'),
        ('products', '0009_alter_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailaftervariation',
            name='variation_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variations.variationoption'),
        ),
    ]
