# Generated by Django 4.1 on 2024-03-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='products/featured_image/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('pre-order', 'Pre Order'), ('regular', 'Regular'), ('manage_stock', 'manage stock')], default='regular', max_length=20),
        ),
    ]
