# Generated by Django 4.1 on 2024-03-17 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_delete_variationgroup'),
        ('products', '0012_tags_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variation_options',
            field=models.ManyToManyField(through='products.ProductDetailAfterVariation', to='variations.variationoption'),
        ),
        migrations.RemoveField(
            model_name='productdetailaftervariation',
            name='variation_options',
        ),
        migrations.AddField(
            model_name='productdetailaftervariation',
            name='variation_options',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='variations.variationoption'),
            preserve_default=False,
        ),
    ]
