# Generated by Django 4.1 on 2024-03-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0002_delete_variationgroup'),
        ('products', '0013_product_variation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='category', to='variations.variation'),
        ),
    ]
