# Generated by Django 4.1 on 2024-03-18 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_category_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manage_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('pre-order', 'Pre Order'), ('regular', 'Regular')], default='regular', max_length=20),
        ),
    ]
