# Generated by Django 4.1 on 2024-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_rating_description_alter_rating_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(null=True, related_name='products', to='products.collection'),
        ),
    ]
