# Generated by Django 4.1 on 2024-03-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.collection'),
        ),
    ]
