# Generated by Django 4.1 on 2024-03-20 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetailaftervariation',
            old_name='price_override',
            new_name='price',
        ),
    ]
