# Generated by Django 4.1 on 2024-03-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variations', '0005_alter_variationoption_variation'),
        ('products', '0020_rename_price_override_productdetailaftervariation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailaftervariation',
            name='variation_options',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='variations.variationoption'),
        ),
        migrations.AddConstraint(
            model_name='productdetailaftervariation',
            constraint=models.UniqueConstraint(fields=('variation_options', 'product'), name='unique_variation_product'),
        ),
    ]
